package com.cts.springboot.boothibernet.dao;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.transaction.Transactional;

import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.cts.springboot.boothibernet.entity.Product;



@Repository
@Transactional
public class ProductDaoHibernateImpl implements IProductDao {
	
	
	@Autowired
	private EntityManager em;
	// dependency
	
	
	
	public ProductDaoHibernateImpl() {
		// TODO Auto-generated constructor stub
	
	}
	
	@Override
	public List<Product> findAll() {
		// TODO Auto-generated method stub
		// get the Hibernate Session object (Persistant Context)
		
		
		// Student : entity class name
		// query generated by Hibernate is returned as Object
		Query query =  this.em.createQuery("from Product", Product.class);
		List<Product> products = query.getResultList();
		return products;
	}

	@Override
	public Product findById(Integer id) {
		// TODO Auto-generated method stub
		// get the Hibernate Session object (Persistant Context)
		// every time new session object is required
		// as persistant context works within a method
		Product product = this.em.find(Product.class, id);
		
		return product;
	}

	@Override
	public boolean add(Product product) {
		// TODO Auto-generated method stub
		
		this.em.merge(product);
		
		return true;
	}

	@Override
	public boolean update(Product product) {
		// TODO Auto-generated method stub
		this.em.merge(product);
		return true;
	}

	@Override
	public boolean delete(Integer id) {
		// TODO Auto-generated method stub
		
		
		this.em.remove(this.findById(id));
		return true;
	}

}
